apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flowcom

labels:
  - includeSelectors: false
    pairs:
      app: flowcom

resources:
  - mongo.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
